### ISSUE TITLE
Provide a Scala Native plugin 

### ISSUE THREAD

**Issue by keynmol** [indoorvivants/sbt-vcpkg#46]
Right now I have 3 versions of `vcpkgNativeConfig` laying about:

1. https://github.com/keynmol/twotm8/blob/main/build.sbt#L200
2. https://github.com/indoorvivants/sn-roguelike/blob/main/build.sbt#L70 (sort of, but same purpose)
3. https://github.com/indoorvivants/sn-bindgen-examples/blob/main/build.sbt#L237
4. https://github.com/indoorvivants/roach/blob/main/build.sbt#L51 (**this is the most up-to-date, use this for reference**)

What it does is pretty simple, but there are important caveats:

1. Not all libraries have pkg-config - all we can do is speculatively add library files and header paths and sort of hope for the best
2. The linking arguments from Scala Native's default config need to come _after_ the arguments from vcpkg. 
     
     If you have a libpq.dylib installed globally, then SN will gladly link against the dynamic version, instead of the static one available literally 2 arguments over.
3. When falling back to guesswork, we need to use the transitive closure of dependencies specified in the module - pkg-config files already use that information, but if there's no `.pc` files we need to do it manually.

To that end I believe we should:

- [ ] **core** Provide a `vcpkgNativeConfigure(m: Vcpkg, options: ...): ScalaNativeConfig` (returns custom case class, not affiliated with Scala Native build tooling) with the logic adapted from all the variants above.
- [ ] **sbt-vcpkg** Provide a `VcpkgNativePlugin` that automatically configures the project where ScalaNativePlugin is enabled
       I don't think there is a way to provide two plugins in the same module without forcing a Scala Native plugin dependency, but I need to try that.
- [ ] **mill-vcpkg** Mill is cool and all that and that functionality, I think, can be implemented in the same module because SN support is built-in. @Baccata can you confirm please?

**Comment by Baccata** [comment]
>  mill-vcpkg Mill is cool and all that and that functionality, I think, can be implemented in the same module because SN support is built-in. @Baccata can you confirm please? 

Mill does indeed provide SN support out of the box.
